### PR TITLE
Update cakehax

### PR DESCRIPTION
**Pull request by mariogamer2**

### CODE REVIEW

**Comment by mid-kid** [comment]
Just letting you know this is incredibly useless and you shouldn't bother checking if the submodules are up-to-date. The changes that happened to CakeHax since the latest submodule update have zero effect on CakesFW itself (i.e. chainloader payload updates - only useful for rxTools/Decrypt9).

**Comment by mariogamer2** [comment]
Ok sorry,I'm just a n00b ;)

**Comment by ghost** [comment]
At least he isn't proofreading your readme for grammar nazi stuff. Count yourself lucky, mid-kid. :p

**Comment by mariogamer2** [comment]
?

**Comment by mid-kid** [comment]
@idgrepthat Yeah, I was just reading his contribution log... *shudders in angst*

**Pull request merged**
