### PR TITLE
Fixed Windows not liking it

### PR DESCRIPTION
**Pull request by ghost**
Just moved sdmmc, as you said.

### CODE REVIEW

**Comment by ghost** [comment]
Yeah, Notepad++ for ya. I'll do so, later. If you want, this request could be ignored and perhaps you could make the changes yourself, instead of waiting?

**Comment by b1l1s** [comment]
We don't have that many PR anyways, I'm not gonna start ignoring one now :P I'll wait.

**Comment by ghost** [comment]
Done

**Comment by mid-kid** [comment]
:+1: (Nevermind, won't pressure you to fix that indentation error again)

**Comment by ghost** [comment]
I used GitHubs online editor, this time. Looked fine while editing. Darn encoding >.<

**Pull request merged**
