### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by rzumer**
Fixed the English to make it more professional by Nintendo quality standards.

### CODE REVIEW

**Comment by mid-kid** [comment]
I-i'm not sure if I should take this serious.

**Comment by socram8888** [comment]
Me either. And I kinda prefer the original wording tbh.

**Comment by mariogamer2** [comment]
Me too.

**Comment by icecream42** [comment]
I don't. The aggrandizement of verbal standards is an important milestone in making CakesFW even more trustworthy.

Therefore I hereby declare my agreement with this pull request.

**Comment by philenotfound** [comment]
This isn't a democracy anymore

**Comment by mid-kid** [comment]
Eh. Accepting to humor you. Congratulations, you reached a new accomplishment in life: Update Readme.md.  
Welcome to the CakesFW contributors list. Enjoy your position at the bottom.

**Pull request merged**
