### PR TITLE
Add developer UNITINFO patch

### PR DESCRIPTION
**Pull request by ghost**
Extensively tested in o3DS firmwares 0x50 0x4C, and n3DS firmwares 0x1F 0x1B.
Might prove useful in debugging certain userland crashes.

### CODE REVIEW

**Comment by mid-kid** [comment]
This is a small niché wanted by a small amount of people. I don't see why it should be added into master, instead of keeping it separate.

**Comment by ghost** [comment]
Only reason I can think of it:

It helps debug userland crashes, which can definitely happen if you're using the 3ds_injector; it can determine whether it's a problem within the title or the injector it using the RF patch, for instance.

Of course, this will only be useful if the 3ds_injector patch is ever added

**Comment by ghost** [comment]
I've also been notified that when 9.6 crypto titles are launched with no seed and with devunit enabled it crashes rather than having the endless boot loop, so yet another debug feature

**Comment by kitlith** [comment]
And... this may illustrate why people keep stuff in feature branches, so they don't accidentally add things they didn't mean to, @Wolfvak. (11.0 support probably shouldn't be in a pull request for adding a patch)

**Comment by ghost** [comment]
I actually never intended this to be added. I'll close it now.

**Pull request closed without merging**
